### ISSUE TITLE
No Cars on the Map

### ISSUE THREAD

**Issue by lbenedix** [gorenje/tankmeister#12] opened 2017-05-09 17:30 UTC
The request to the nearest-Endpoint returns only `{"cars":[],"fs":[],"tstamp":"19:28:03 09/05/2017"}`. Another request to cities results in a 500 Error.

**Comment by gorenje** [comment] 2017-05-10 09:44
Hi there,

the 500 error should be fixed with 9843ad1531d678095b57c1761b5335df3586f1d9 (multicity is returning broken json)

the empty cars result is because drivenow has changed their api endpoint and is now not returning car details.

Closing the issue since there the problem is down the line (i.e. drivenow api).

**Closed as completed by gorenje** 2017-05-10 09:44 UTC
